### ISSUE TITLE
Plan after removing --unsafe-pruning?

### ISSUE THREAD

**Issue by wi1dcard** [midl-dev/polkadot-snapshot-generator#1]
Hello there,

Thank you for providing this great project! We'd like to deploy it for our own network. However, after digging into it a little bit, I found that parity just has mentioned that the flag `--unsafe-pruning` is going to be removed in the future versions. Do we have any plan after the flag getting removed?

See: https://github.com/paritytech/substrate/issues/8103

**Comment by nicolasochem** [comment]
`--unsafe-pruning` has been removed, but it does not affect operations.
