### ISSUE TITLE
sha256 checksums

### ISSUE THREAD

**Issue by grenade** [midl-dev/polkadot-snapshot-generator#5]
would it be possible to publish a sha256 checksum of the .lz4 archives along with the other useful info you make available?

i've written some automation that recovers from snapshot download errors, eg: 
```bash
while ! curl \
  --location \
  --output /tmp/polkadot.paritydb.tar.lz4 \
  --retry 999 \
  --retry-max-time 0 \
  --continue-at - \
  https://dot.polkashots.io/snapshot; do
  echo "resuming download..."
done
```
but what would be really useful is to verify that the checksum of the downloaded file, matches what the download server says it should be. eg:
```bash
while [ "${expected_sha}" != "$(sha256sum ${local_file_path} 2> /dev/null | cut -d ' ' -f 1)" ]; do
  curl -o ${local_file_path} ...
done
```

**Comment by nicolasochem** [comment]
hi! Thanks for the suggestion, however we are switching off the project due to availaibility of warp sync.
